# Generated by Django 5.0.2 on 2024-02-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_tohome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
                ('farmer_name', models.CharField(max_length=20)),
            ],
        ),
    ]
