# Generated by Django 5.0.2 on 2024-02-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fresh_tohome', '0002_add_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Farmers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateTimeField(auto_created=True)),
                ('farmer_name', models.CharField(max_length=20)),
                ('farmer_address', models.TextField()),
                ('farmer_contact', models.IntegerField()),
                ('farmer_product', models.CharField(max_length=20)),
                ('product_price', models.IntegerField()),
            ],
        ),
    ]
